# Topic 1 · Naming My Feelings (draft 1; not published). Build: python3 build.py topics/01-naming-my-feelings.py
# Lee leads this story (Tee led Calm Corner). Four core feelings for K: happy, sad, mad, worried.
# Spanish uses feeling NOUNS (alegría, tristeza, enojo, preocupación) so lines are not gendered.
# New Flow art needed: ff_hero, ff_worried, ff_notice, ff_proud.

FACES = [  # (art, EN, ES, KR): the four core feelings
    ('lee_happy', 'happy', 'alegría', 'kontan'),
    ('lee_sad', 'sad', 'tristeza', 'tris'),
    ('lee_mad', 'mad', 'enojo', 'fache'),
    ('lee_worried', 'worried', 'preocupación', 'enkyete'),
]
CLUES = [  # (art, EN, ES, KR): feeling + body clue, for the desk strips
    ('lee_happy', 'Happy: I smile.', 'Alegría: sonrío.', 'Kontan: mwen souri.'),
    ('lee_sad', 'Sad: my eyes get wet.', 'Tristeza: mis ojos se mojan.', 'Tris: je m mouye.'),
    ('lee_mad', 'Mad: my face gets hot.', 'Enojo: mi cara se calienta.', 'Fache: figi m cho.'),
    ('lee_worried', 'Worried: my tummy feels funny.', 'Preocupación: siento cosquillas en la panza.', 'Enkyete: vant mwen fè m dwòl.'),
]

TOPIC = dict(
    num=1,
    slug='01-naming-my-feelings',
    file_prefix='My-Feelings',
    deck_slug='my-feelings',
    title='My Feelings',
    full_title='Naming My Feelings',
    title_lines=['MY', 'FEELINGS'],
    subtitle='I can name how I feel',
    value='Respectful',
    part='Skills I can use',
    promise=dict(
        en='I can name my feeling. I can say, "I feel ___."',
        es='Puedo decir lo que siento: "Siento ___."',
        kr='Mwen ka di sa m santi: "Mwen santi m ___."',
    ),
    card_line='I can name how I feel.',
    song=dict(video=None, length='about 1 minute 24 seconds', poster_at=2.5),
    choices=FACES,
    choices_head=dict(en='How do I feel?', es='¿Qué siento?', kr='Kijan m santi m?'),
    deck=dict(
        eyebrow='Morning Meeting · Respectful',
        s1=dict(bubble='Every feeling has a name!', words='feelings · sentimientos · santiman', img='ff_hero', pos='center 25%'),
        s2=dict(img='class_breathe', pos='center 35%'),
        s3=dict(
            title='WHAT DID LEE DO?',
            layout='grid',
            panels=[
                dict(img='ff_worried', pos='5% 35%', num='1', label='Big feeling.', color='var(--sky)'),
                dict(img='ff_notice', pos='0% 30%', num='2', label='Notice.', color='var(--orange)'),
                dict(img='c_grownup', pos='35% 35%', num='3', label='Name it.', color='var(--green)'),
                dict(img='ff_proud', pos='10% 35%', num='4', label='Feel better.', color='var(--red)'),
            ],
            say='I notice my body. I name my feeling. "I feel worried."',
        ),
        s4=dict(
            title='HOW DOES LEE FEEL?',
            img='ff_worried',
            pos='center 35%',
            stem='Lee feels ___.',
            faces=[('lee_happy', 'happy'), ('lee_worried', 'worried'), ('lee_mad', 'mad')],
        ),
        s5=dict(
            title='MY FACE, MY BODY, MY WORDS',
            img='kiara_hi5',
            pos='center 30%',
            q='My friend gives me a high five.',
            q2='I feel...',
            choice_fit='contain',
            choices=[(k, en) for k, en, es, kr in FACES],
        ),
        s6=dict(
            vow='I can name<br>my feeling.',
            stem='Right now, I feel ___.',
            choices=FACES,
            img='promise',
        ),
        s7=dict(
            steps=[('🧍', 'Stand up'), ('🙂', 'Calm face'), ('👣', 'Walk'), ('⭐', 'Ready to learn')],
            pill='I know how I feel!',
            img='leave',
        ),
        notes=[
            dict(
                name='Title &amp; Promise',
                rubric='R2',
                script='Point to your own face and make a big smile, then a sad face. “Our faces and bodies tell us how we feel. Every feeling has a name. Today we learn to say how we feel.” Say together: “Every feeling has a name.”',
                look=['Eyes on the slide or on you', 'Students copy your faces', 'Students repeat “Every feeling has a name”'],
                breaks=['If faces get silly: “Show me a happy face. Now a calm face.” End on calm, then move on.'],
                support=['Sit near any student who has had a hard morning; never ask a student to share a feeling they did not choose to share'],
                language=['Feeling words are new for many students: say each one with a matching face', 'Spanish: sentimientos · Kreyòl: santiman'],
                move='Equity stick: pull one name and ask, “Show me a happy face.” Any happy face is a full answer.',
                aside='All feelings are okay. Feelings are not good or bad; some feel good and some feel hard. Say it that way every time.',
            ),
            dict(
                name='Regulate · Get Calm First',
                rubric='R1',
                script='Model the gesture with them every time. “Smell the flower. Blow out the candle. Long and slow. Three times.” Do it with the class, not from the front.',
                look=['Exhale longer than inhale', 'Shoulders drop', 'Gesture copied'],
                breaks=['If silliness: model silently once, then invite them back.'],
                support=['Breathe audibly beside any student who cannot settle'],
                language=['No language demand; gesture carries it', 'Same two gestures used in every K–2 lesson'],
                move='LiveSchool: award a point to a student who breathes all three times with you. Name the behavior: “You breathed slow three times.”',
                aside='Ask: “How does your body feel now?” One or two quick answers. This is the first naming practice of the day.',
            ),
            dict(
                name='Orient · The Story',
                rubric='R2, R3',
                script='Point to each picture as you tell it. “It was Lee’s turn to read out loud. Her tummy felt funny and her hands felt shaky. She noticed her body. She named her feeling: ‘I feel worried.’ She told her teacher. Her teacher said, ‘Thank you for telling me. Let’s read together.’ Lee read, and she felt proud.” Then have the class say together: “I notice my body. I name my feeling.”',
                look=['Students follow the pictures in order', 'Whole class repeats the We say line'],
                breaks=['If students say Lee is a baby for being worried: “Everyone feels worried sometimes. Even grown-ups. Lee was brave to say it.”'],
                support=['Point to each panel as the teacher narrates'],
                language=['Four pictures, two words each; numbers carry the order', 'Act out “tummy feels funny” by rubbing your tummy'],
                move='Equity stick: “Which picture shows Lee naming her feeling? Point.” Pointing is a full answer.',
                aside='Naming a feeling makes it smaller. Lee did not have to hide it or act it out; she said it.',
            ),
            dict(
                name='Connect · Turn and Talk',
                rubric='R3, R4',
                script='Show knee to knee with a student partner. “Turn knee to knee. Look at Lee’s face and body. Tell your partner: Lee feels ___.” Give 30 seconds, then ring back. Ask one pair: “How did you know?”',
                look=['Partners face each other', 'Students name worried or point to the worried face', 'Some students name a body clue'],
                breaks=['If a pair is stuck: kneel in and say the stem with them.', 'If partners argue: “Take turns. You go first, then you.”'],
                support=['Pair any student who needs support with a steady partner before the lesson starts'],
                language=['Pointing to a face is a complete answer', 'Spanish: “Siente preocupación” · Kreyòl: “Li santi l enkyete”'],
                move='Equity stick: call two names to share. Praise the clue: “You saw her worried eyebrows. Great noticing!”',
                aside='',
            ),
            dict(
                name='Practice · Watch Me, Then Show Me',
                rubric='R3, R4, R5',
                script='Read the scene. “My friend gives me a high five. I feel…” Invite one student to show the face and say the sentence: “I feel happy.” Ask the class, “What clue did you see?” Then read two more: “My tower falls down.” “It is my turn to read out loud.” A new student models each one. Then the whole class shows each face together.',
                look=['A student shows a face and says “I feel ___.”', 'Class names the clue they saw', 'Whole class practices all four faces'],
                breaks=['Excellent model: “Show the class again. Everyone, what feeling was that?”', 'Partly right model: “You showed the face. Now say the sentence: I feel ___.”', 'Silly model: “Thank you. Let’s see it the calm way.” Call a new student; no commentary.'],
                support=['Hold up the four face cards so students can point instead of naming'],
                language=['Four faces with words; students can point instead of naming', 'Model “I feel ___.” as a sentence everyone says', 'Spanish: “Siento ___.” · Kreyòl: “Mwen santi m ___.”'],
                move='LiveSchool: award the student model a point for using the full sentence. Name it out loud.',
                aside='Students model, not the teacher. Accept any feeling a student can explain; there is no single right answer for “My tower falls down.”',
            ),
            dict(
                name='Commit · My Promise Today',
                rubric='R2, R5',
                script='Put your hand on your heart. “Say it with me: I can name my feeling.” Then: “Point to how you feel right now.” Model it first: “Right now, I feel happy.”',
                look=['Every student says the promise', 'Every student points to one face'],
                breaks=['If a student does not choose: offer two faces and let them point.', 'Never push a student to explain a hard feeling in front of the class.'],
                support=['Check in quietly later with any student who points to sad, mad, or worried'],
                language=['Hand on heart carries the promise', 'Spanish: Puedo decir lo que siento · Kreyòl: Mwen ka di sa m santi'],
                move='Equity stick: pull three names: “Which face did you point to?” Pointing counts.',
                aside='A student who points to sad, mad, or worried gets a quiet check-in after the meeting, not a public conversation.',
            ),
            dict(
                name='Transition · How We Leave',
                rubric='R1, R4, R5',
                script='“How we leave is how we start our learning. Stand up. Calm face. Walk. Ready to learn. Let’s practice.” Do not time this at K–2.',
                look=['Calm faces and bodies while moving', 'Calm walking, not rushing'],
                breaks=['“Let’s try that again. Back to your spot.” Rebuild clean, no commentary on individuals.'],
                support=['Stand at the destination, not behind the group'],
                language=['Four icons, four words', 'No timing pressure at this age'],
                move='LiveSchool: award a point to the table that walks with calm bodies the whole way.',
                aside='Name feelings out loud all day: “You look excited. You look frustrated.” Students learn the words by hearing them.',
            ),
        ],
    ),
    poster=dict(
        header_img='ff_hero',
        footer_img='thumbs',
        choice_fit='contain',
        panels=[
            dict(img='lee_happy', pos='center center', fit='contain', color='var(--gold)', symbol='1', en='Happy: I smile. My body feels light.', es='Alegría: sonrío. Mi cuerpo se siente ligero.', kr='Kontan: mwen souri. Kò m lejè.'),
            dict(img='lee_sad', pos='center center', fit='contain', color='var(--sky)', symbol='2', en='Sad: my eyes get wet. My body feels heavy.', es='Tristeza: mis ojos se mojan. Mi cuerpo se siente pesado.', kr='Tris: je m mouye. Kò m lou.'),
            dict(img='lee_mad', pos='center center', fit='contain', color='var(--red)', symbol='3', en='Mad: my face gets hot. My hands get tight.', es='Enojo: mi cara se calienta. Mis manos se aprietan.', kr='Fache: figi m cho. Men m sere.'),
            dict(img='lee_worried', pos='center center', fit='contain', color='var(--orange)', symbol='4', en='Worried: my tummy feels funny.', es='Preocupación: siento cosquillas en la panza.', kr='Enkyete: vant mwen fè m dwòl.'),
        ],
    ),
    minibook=dict(
        cover_title='My<br>Feelings',
        cover_img='ff_hero',
        cover_pos='center 25%',
        cover_es='Lo que siento',
        cover_kr='Santiman mwen',
        pages=[
            dict(img='lee_faces', pos='center center', fit='contain', en='I have lots of feelings. All feelings are okay.', es='Tengo muchos sentimientos. Todos los sentimientos están bien.', kr='Mwen gen anpil santiman. Tout santiman bon.'),
            dict(img='lee_happy', pos='center 30%', fit='contain', en='When I feel happy, I smile. My body feels light.', es='Cuando siento alegría, sonrío. Mi cuerpo se siente ligero.', kr='Lè m kontan, mwen souri. Kò m lejè.'),
            dict(img='lee_sad', pos='center 30%', fit='contain', en='When I feel sad, my eyes get wet. My body feels heavy.', es='Cuando siento tristeza, mis ojos se mojan. Mi cuerpo se siente pesado.', kr='Lè m tris, je m mouye. Kò m lou.'),
            dict(img='lee_mad', pos='center 30%', fit='contain', en='When I feel mad, my face gets hot. My hands get tight.', es='Cuando siento enojo, mi cara se calienta. Mis manos se aprietan.', kr='Lè m fache, figi m cho. Men m sere.'),
            dict(img='lee_worried', pos='center 30%', fit='contain', en='When I feel worried, my tummy feels funny.', es='Cuando siento preocupación, siento cosquillas en la panza.', kr='Lè m enkyete, vant mwen fè m dwòl.'),
            dict(img='c_grownup', pos='35% 35%', en='I can say it: “I feel ___.” A grown-up can help.', es='Puedo decirlo: “Siento ___.” Un adulto me puede ayudar.', kr='Mwen ka di l: “Mwen santi m ___.” Yon granmoun ka ede m.'),
        ],
        back_img='promise',
        back_prompt='Color a star when I name my feeling.',
    ),
    centers=dict(
        sort=dict(
            title='SORT IT: HOW DOES IT FEEL?',
            yes=dict(symbol='☺', en='Feels good', es='Se siente bien', kr='Santi l byen'),
            no=dict(symbol='☹', en='Feels hard', es='Se siente difícil', kr='Santi l difisil'),
            cards=[
                ('building', 'center 40%', 'yes'),
                ('nadege_hurt', '40% 35%', 'no'),
                ('kiara_hi5', 'center 30%', 'yes'),
                ('tower_falls', 'center 45%', 'no'),
                ('ff_proud', 'center 35%', 'yes'),
                ('tee_overwhelmed', '30% 30%', 'no'),
                ('puzzle', 'center 40%', 'yes'),
                ('ff_worried', 'center 35%', 'no'),
            ],
        ),
        seq=dict(
            cards=[
                ('ff_worried', 'Big feeling'),
                ('ff_notice', 'Notice'),
                ('c_grownup', 'Name it'),
                ('ff_proud', 'Feel better'),
            ],
            print_order=[2, 0, 3, 1],
        ),
        roleplay=dict(
            prompt='I feel...',
            dirs=[('🃏', 'pick'), ('🙂', 'show the face'), ('🗣️', 'say it')],
            scenes=[
                ('kiara_hi5', 'center 30%', 'My friend gives me a high five.', 'Mi amiga me choca la mano.', 'Zanmi m ban m yon tap.'),
                ('tower_falls', 'center 45%', 'My tower falls down.', 'Mi torre se cae.', 'Gwo kay blòk mwen tonbe.'),
                ('ff_worried', 'center 35%', 'It is my turn to read out loud.', 'Me toca leer en voz alta.', 'Se tou pa m pou m li fò.'),
                ('nadege_hurt', '40% 35%', 'My friend gets hurt.', 'Mi amiga se lastima.', 'Zanmi m blese.'),
            ],
        ),
        strips=dict(
            title='DESK STRIPS: MY FEELING CLUES',
            choices=CLUES,
            head=dict(en='I feel...', es='Siento...', kr='Mwen santi m...'),
        ),
        color=dict(
            title='HOW DO I FEEL TODAY?',
            trace='lee_happy',
            trace_opts=dict(blur=1.2, thicken=1),
            prompt='Draw your face. How do you feel today?',
            prompt_es='Dibuja tu cara. ¿Qué sientes hoy?',
            prompt_kr='Desine figi ou. Kijan ou santi w jodi a?',
        ),
    ),
    family=dict(
        hero='ff_hero',
        hero_pos='center 25%',
        en=dict(
            t='My Feelings',
            eb='This week in Morning Meeting · Kindergarten to 2nd Grade',
            intro='Your child is learning to name feelings: happy, sad, mad, and worried. Children are learning to notice clues in their face and body and to say, “I feel ___.” All feelings are okay. Naming a feeling helps it feel smaller.',
            sayh='At school we say:',
            say='I notice my body. I name my feeling. “I feel ___.”',
            ch='Feeling faces',
            th='Try at home',
            tips=[
                '<b>Feelings check:</b> at dinner or bedtime, ask, “How did you feel today?” Let your child point to a face.',
                '<b>Name your own:</b> “I feel tired.” “I feel happy you are home.” Children learn the words from you.',
                '<b>Read faces:</b> in a book or a show, ask, “How does she feel? How do you know?”',
            ],
            ft='Questions? Talk with your child’s teacher.',
        ),
        es=dict(
            t='Lo que siento',
            eb='Esta semana en la Reunión de la Mañana · Kínder a 2.º grado',
            intro='Su hijo o hija está aprendiendo a nombrar sentimientos: alegría, tristeza, enojo y preocupación. Aprende a notar las señales de su cara y su cuerpo y a decir: “Siento ___.” Todos los sentimientos están bien. Nombrarlos ayuda.',
            sayh='En la escuela decimos:',
            say='Noto mi cuerpo. Nombro lo que siento. “Siento ___.”',
            ch='Caras de sentimientos',
            th='Practiquen en casa',
            tips=[
                '<b>Hablen de sentimientos:</b> en la cena, pregunte: “¿Qué sentiste hoy?” Deje que señale una cara.',
                '<b>Nombre los suyos:</b> “Siento cansancio.” “Siento alegría de verte.” Los niños aprenden las palabras de usted.',
                '<b>Lean caras:</b> en un libro o un programa, pregunte: “¿Qué siente ella? ¿Cómo lo sabes?”',
            ],
            ft='¿Preguntas? Hable con el maestro o la maestra de su hijo o hija.',
        ),
        kr=dict(
            t='Santiman mwen',
            eb='Semèn sa a nan Reyinyon Maten · Kindègadenn rive 2yèm ane',
            intro='Pitit ou ap aprann bay santiman yo non: kontan, tris, fache, ak enkyete. Timoun yo ap aprann remake siy nan figi yo ak nan kò yo, epi pou yo di: “Mwen santi m ___.” Tout santiman bon. Lè ou bay yon santiman non, li vin pi piti.',
            sayh='Nan lekòl la nou di:',
            say='Mwen remake kò m. Mwen bay santiman m non. “Mwen santi m ___.”',
            ch='Figi santiman',
            th='Eseye lakay ou',
            tips=[
                '<b>Tcheke santiman:</b> nan dine oswa anvan dòmi, mande: “Kijan ou te santi w jodi a?” Kite pitit ou montre yon figi.',
                '<b>Di pa w yo:</b> “Mwen santi m fatige.” “Mwen kontan ou lakay.” Timoun yo aprann mo yo nan men ou.',
                '<b>Li figi:</b> nan yon liv oswa yon emisyon, mande: “Kijan li santi l? Kijan ou konnen?”',
            ],
            ft='Ou gen kesyon? Pale ak pwofesè pitit ou a.',
        ),
    ),
    guide=dict(
        images=[('ff_worried', 300, 168), ('ff_proud', 300, 168)],
        glance=[
            ('Goal', 'Students name four feelings (happy, sad, mad, worried), notice one body clue for each, and say “I feel ___.”'),
            ('Time', '15 minutes in Morning Meeting, in place of the general lesson. Centers run during the week.'),
            ('When', 'Teach first in the toolkit, early in the year. Every later topic uses these feeling words.'),
            ('In the bundle', 'Student deck (7 slides, press N for notes) · Poster (letter and 11×17) · Center kit (sort, sequence, act it out, desk strips, coloring) · Mini book · Family half-sheet'),
            ('Words we use', '“Every feeling has a name.” · “I notice my body. I name my feeling.” · “I feel ___.”'),
        ],
        before=[
            'Hang the poster at child height near your meeting space or the calm corner. Students point to it all week.',
            'All feelings are okay. Say “feels good” and “feels hard,” never “good feelings” and “bad feelings.”',
            'Never ask a student to name a feeling in front of the class that they did not choose to share. Check in privately instead.',
            'Tape a desk strip at the table of any student who needs the feeling faces close by.',
            'Pair students who need support with a steady turn-and-talk partner before the lesson starts.',
        ],
        slides=[
            ('1 · Title & Promise (R2)', 'Make a happy face, then a sad face. “Our faces and bodies tell us how we feel. Every feeling has a name.” Say together: “Every feeling has a name.”', 'Students copy your faces and repeat the line.', 'Equity stick: “Show me a happy face.”'),
            ('2 · Get Calm First (R1)', 'Do it with them. “Smell the flower. Blow out the candle. Long and slow. Three times.” Then ask, “How does your body feel now?”', 'Exhale longer than inhale; shoulders drop.', 'LiveSchool point: “You breathed slow three times.”'),
            ('3 · What Did Lee Do? (R2, R3)', 'Point to each picture. “It was Lee’s turn to read. Her tummy felt funny. She noticed her body. She named it: ‘I feel worried.’ She told her teacher, and she felt better.” Class says: “I notice my body. I name my feeling.”', 'Students follow the pictures; whole class repeats the line.', 'Equity stick: “Which picture shows Lee naming her feeling? Point.”'),
            ('4 · Turn and Talk (R3, R4)', 'Model knee to knee. “Look at Lee. Tell your partner: Lee feels ___.” 30 seconds, then ask one pair, “How did you know?”', 'Partners take turns; some name a body clue.', 'Equity stick: two shares. Praise the clue they noticed.'),
            ('5 · Watch Me, Then Show Me (R3, R4, R5)', 'Read: “My friend gives me a high five. I feel…” A student shows the face and says, “I feel happy.” Repeat with “My tower falls down” and “It is my turn to read out loud.” Then everyone shows all four faces.', 'Students use the full sentence; class names the clue.', 'LiveSchool point for the full sentence.'),
            ('6 · My Promise Today (R2, R5)', 'Hand on heart. “Say it with me: I can name my feeling.” Then: “Point to how you feel right now.”', 'Every student says the promise and points to one face.', 'Equity stick: three names. Pointing counts.'),
            ('7 · How We Leave (R1, R4, R5)', '“Stand up. Calm face. Walk. Ready to learn.” Do not time this at K–2.', 'Calm bodies while moving; calm walking.', 'LiveSchool point for the table that walks with calm bodies the whole way.'),
        ],
        bridges=[
            ('Excellent', '“Show the class again. Everyone, what feeling was that? What clue did you see?”'),
            ('Partly right', '“You showed the face. Now say the sentence: I feel ___.”'),
            ('Silly', '“Thank you. Let’s see it the calm way.” Call a new student. No commentary.'),
        ],
        centers=[
            ('Sort It', 'Sort mat (landscape page) and 8 cut picture cards.', '“Look at each picture. Does it feel good or feel hard? Put it on the side where it goes.”', '4 cards on Feels good, 4 on Feels hard. Accept any sort a student can explain.'),
            ('Put It in Order', 'Sequencing mat and 4 cut cards.', '“Put Lee’s story in order: first, next, then, last. Tell your partner the story.”', 'Students retell: big feeling, notice, name it, feel better.'),
            ('Act It Out', '4 role-play cards in a stack.', '“Pick a card. Read it with me. Show the face. Say: I feel ___.”', 'Each student shows a face and says the sentence.'),
            ('Feeling Clues', 'Desk strips, one per student.', '“Point to each face. Say the feeling and the clue.”', 'Each student names all four feelings.'),
            ('Color', 'Coloring page and crayons.', '“Color Lee. In the box, draw your face. How do you feel today?”', 'A face drawing and a feeling word, said or written.'),
        ],
        keys=[
            ('Sort, Feels good: ', 'friends building with blocks · Kiara’s high five · Lee reading proudly · Tee and Nadege doing a puzzle.'),
            ('Sort, Feels hard: ', 'Nadege gets hurt · Tee’s tower falls · Tee finds the work too hard · Lee waits to read, worried.'),
            ('Put It in Order: ', '1 Lee feels worried in the reading circle · 2 Lee notices her body · 3 Lee tells her teacher · 4 Lee reads and feels proud.'),
        ],
        minibook=[
            'For a child who needs extra practice with feeling words: one who shuts down, says “fine” to everything, or acts feelings out instead of saying them.',
            'Read it one-on-one at a calm time. Make each face together and touch the body clue.',
            'Read it every day for a week. Let the child turn the pages and point to the faces.',
            'On the back, the child colors a star each day they name a feeling. Celebrate every star.',
        ],
        when_title='When naming feelings gets tricky',
        when_intro='Follows the Responsive Behavior Plan: the adult response is the intervention. Fewer words as escalation rises.',
        when=[
            ('A student cannot find the word. ', 'Offer two faces: “Do you feel mad or worried?” Pointing counts.'),
            ('A student says “fine” to everything. ', 'Name what you see, gently: “Your fists look tight. Maybe mad?” Then wait.'),
            ('A student is too upset to talk. ', 'Do not ask for words yet. Get calm first: breathe together or offer the calm corner. Name the feeling later.'),
            ('A student names a feeling about home or someone hurting them. ', 'Listen, thank them, and follow your school’s reporting steps. Tell the counseling team the same day.'),
            ('A student names mad and then acts unsafe. ', 'Safety first. Use Topic 7, Gentle Hands, and the Responsive Behavior Plan.'),
        ],
        when_outro='Next in the toolkit: Topic 2, Using the Calm Corner, and Topic 3, Belly Breathing.',
    ),
    site=dict(
        hero_img='ff_hero',
        hero_alt='Lee and Tee holding up feeling face cards',
        hero_pos='center 25%',
        deck_desc='Get calm, watch Lee name her feeling, turn and talk, practice four feeling faces, make a promise, and leave calmly.',
        guide_desc='The lesson at a glance, the slide-by-slide script, how to run the centers, and what to do when naming feelings gets tricky.',
        poster_hint='Hang it at child height near your meeting space or the calm corner.',
        centers_desc='Sort mat and 8 picture cards, sequencing mat and cards, role-play cards, feeling clue strips, and a coloring page.',
        minibook_desc='A read-together book for students who need more practice with feeling words. Read it one on one and make each face together.',
        family_desc='What your child is learning, what we say at school, and three ways to talk about feelings at home. One page per language, two half-sheets per page.',
    ),
)
