# Topic 2 · Using the Calm Corner (draft 1, built through the builder)
# Calm-corner tools only (no fidgets). Steps: notice, walk, get calm, come back.
CHOICES = [  # (art, EN, ES, KR): what I can do IN the calm corner
    ('c_breathe', 'Smell and blow', 'Oler y soplar', 'Pran sant epi soufle'),
    ('tee_feather', 'Feather breath', 'Respirar con la pluma', 'Respire ak plim nan'),
    ('lee_faces', 'Name my feeling', 'Decir lo que siento', 'Di sa m santi'),
    ('lee_breathe', 'Sit and rest', 'Sentarme a descansar', 'Chita repoze'),
]
STEPS = [  # (art, EN, ES, KR): the calm corner routine
    ('tee_overwhelmed', 'I notice a big feeling.', 'Noto un sentimiento grande.', 'Mwen remake yon gwo santiman.'),
    ('to_corner', 'I walk to the calm corner.', 'Camino al rincón de calma.', 'Mwen mache al nan kwen kalm nan.'),
    ('in_corner', 'I use a calm tool.', 'Uso una herramienta de calma.', 'Mwen sèvi ak yon zouti pou kalme.'),
    ('to_rug', 'I come back to learn.', 'Regreso a aprender.', 'Mwen retounen pou m aprann.'),
]

TOPIC = dict(
    num=2, folder='02-calm-corner', slug='calm-corner', prefix='Calm-Corner',
    zip_slug='using-the-calm-corner', zip_folder='Using-the-Calm-Corner',
    title='Using the Calm Corner', short='Calm Corner', part='Skills I can use', value='Responsible',
    title_lines=['CALM', 'CORNER'], sub='get calm, come back',
    promise=('I get calm. Then I come back to learn.', 'Me calmo. Luego regreso a aprender.',
             'Mwen kalme m. Apre sa, mwen retounen pou m aprann.'),
    song=None,  # added after Marlitha makes the song in Suno
    choices=CHOICES,
    choices_head=('In the calm corner, I can:', 'En el rincón de calma, puedo:', 'Nan kwen kalm nan, mwen ka:'),

    deck=dict(
        s1=dict(eyebrow='Morning Meeting · Responsible', bubble='Big feelings are okay!',
                words='calm · calma · kalm', img='in_corner', pos='center 35%'),
        s2=dict(img='class_breathe', pos='center 35%'),
        s3=dict(title='WHAT DID TEE DO?',
                panels=[('tee_overwhelmed', 'Big feeling.', 'var(--sky)', '30% 30%'),
                        ('to_corner', 'Walk.', 'var(--orange)', '35% 35%'),
                        ('in_corner', 'Get calm.', 'var(--green)', '40% 40%'),
                        ('to_rug', 'Come back.', 'var(--red)', '30% 35%')],
                say='The calm corner helps me get calm. Then I come back.'),
        s4=dict(title='HOW DOES TEE FEEL?', img='tee_overwhelmed', pos='center 30%', stem='Tee feels ___.',
                faces=[('tee_happy', 'happy'), ('tee_worried', 'worried'), ('tee_frustrated', 'frustrated')]),
        s5=dict(title='THE CALM CORNER STEPS', img='tower_falls', pos='center 45%',
                q='My tower falls down.', q2='I feel a big feeling. I...',
                row=[('tee_overwhelmed', '1 Notice'), ('to_corner', '2 Walk'), ('in_corner', '3 Get calm'), ('to_rug', '4 Come back')]),
        s6=dict(vow='I get calm. I come back.', stem='In the calm corner, I will ___.', choices=[0, 1, 2], img='promise'),
        s7=dict(steps=[('🧍', 'Stand up'), ('🤲', 'Calm body'), ('👣', 'Walk'), ('⭐', 'Ready to learn')],
                pill='Calm bodies, ready minds!', img='leave'),
        notes=[
            ('Title &amp; Promise', 'R2',
             'Point to the calm corner in your room. “This is our calm corner. Everyone gets big feelings. Today we learn how the calm corner helps us get calm and come back.” Say together: “Big feelings are okay.”',
             ['Eyes on the slide or on the real calm corner', 'Students repeat “Big feelings are okay”'],
             ['If students call out who uses the corner most: “The calm corner is for everyone. Even grown-ups need calm.”'],
             ['Sit near any student who uses the calm corner often; this lesson is warm, never a call-out'],
             ['“Calm” is new for many students: say it slowly and drop your shoulders', 'Spanish: calma · Kreyòl: kalm'],
             'Equity stick: pull one name and ask, “Point to our calm corner.” Pointing is a full answer.',
             'The calm corner is a tool, not a time-out. Say it that way every time, and never send a student there as a consequence.'),
            ('Regulate · Get Calm First', 'R1',
             'Model the gesture with them every time. “Smell the flower. Blow out the candle. Long and slow. Three times.” Do it with the class, not from the front.',
             ['Exhale longer than inhale', 'Shoulders drop', 'Gesture copied'],
             ['If silliness: model silently once, then invite them back.'],
             ['Breathe audibly beside any student who cannot settle'],
             ['No language demand; gesture carries it', 'Same two gestures used in every K–2 lesson'],
             'LiveSchool: award a point to a student who breathes all three times with you. Name the behavior: “You breathed slow three times.”',
             'Tell students: “This is one of the tools in our calm corner.”'),
            ('Orient · The Story', 'R2, R3',
             'Point to each picture as you tell it. “Tee was working. The work felt too hard. He got a big feeling in his body. He walked to the calm corner. He used a calm tool and got calm. Then he came back to the rug, ready to learn.” Then have the class say together: “The calm corner helps me get calm. Then I come back.”',
             ['Students follow the pictures in order', 'Whole class repeats the We say line'],
             ['If students say Tee is in trouble: “No. Tee chose a tool. That is a smart choice.”'],
             ['Point to each panel as the teacher narrates'],
             ['Four pictures, two words each; numbers carry the order', 'Act out each step with your body as you say it'],
             'Equity stick: “Which picture shows Tee getting calm? Point.” Pointing is a full answer.',
             'Name the come-back step every time. The calm corner is a short stop, and coming back is part of the routine.'),
            ('Connect · Turn and Talk', 'R3, R4',
             'Show knee to knee with a student partner. “Turn knee to knee. Look at Tee. Tell your partner: Tee feels ___.” Give 30 seconds, then ring back.',
             ['Partners face each other', 'Students name a big feeling or point to a face', 'Partners take turns'],
             ['If a pair is stuck: kneel in and say the stem with them.', 'If partners argue: “Take turns. You go first, then you.”'],
             ['Pair any student who needs support with a steady partner before the lesson starts'],
             ['Pointing to a face is a complete answer', 'Worried and frustrated are both right. Accept any big feeling.', 'Spanish: preocupado, frustrado · Kreyòl: enkyete, fristre'],
             'Equity stick: call two names to share. Praise the frame: “You said: Tee feels worried. Full sentence!”',
             ''),
            ('Practice · Watch Me, Then Show Me', 'R3, R4, R5',
             'Read the scene. “My tower falls down. I feel a big feeling. I…” Invite one student to model the four steps using your real calm corner: show the big feeling, walk to the corner, do one calm tool, and walk back to the rug. Narrate each step and ask the class, “What did they do first? Next?” Then the whole class practices the steps in place with their bodies.',
             ['A student models all four steps, including coming back', 'Class names the steps in order', 'Whole class rehearses smell and blow'],
             ['Excellent model: “Show the class again. Everyone, what step was last?”', 'Partly right model: “You got calm. Now show us the last step: come back. Try again.”', 'Silly model: “Thank you. Let’s see it the calm way.” Call a new student; no commentary.'],
             ['Stand at the real calm corner and point to each tool as the student uses it'],
             ['Four pictures with numbers; students can point instead of naming', 'Model “I come back” as a sentence everyone says'],
             'LiveSchool: award the student model a point for coming back to the rug. Name it out loud.',
             'Students model, not the teacher. One friend in the calm corner at a time.'),
            ('Commit · My Promise Today', 'R2, R5',
             'Put your hand on your heart. “Say it with me: I get calm. I come back.” Then: “Point to the calm tool you will use in the calm corner.”',
             ['Every student says the promise', 'Every student points to one tool'],
             ['If a student does not choose: offer two pictures and let them point.'],
             ['Notice and name a student’s calm-corner choice later in the day'],
             ['Hand on heart carries the promise', 'Spanish: Me calmo. Regreso. · Kreyòl: Mwen kalme m. Mwen retounen.'],
             'Equity stick: pull three names: “Which tool did you pick?” Pointing counts.',
             ''),
            ('Transition · How We Leave', 'R1, R4, R5',
             '“How we leave is how we start our learning. Stand up. Calm body. Walk. Ready to learn. Let’s practice.” Do not time this at K–2.',
             ['Calm bodies while moving', 'Calm walking, not rushing'],
             ['“Let’s try that again. Back to your spot.” Rebuild clean, no commentary on individuals.'],
             ['Stand at the destination, not behind the group'],
             ['Four icons, four words', 'No timing pressure at this age'],
             'LiveSchool: award a point to the table that walks with calm bodies the whole way.',
             'Look for students who use the calm corner and come back on their own this week, and name it when you see it.'),
        ]),

    poster=dict(
        header_img='in_corner', foot_img='thumbs',
        panels=[(STEPS[0][0], 'var(--sky)', '1', *STEPS[0][1:], '30% 30%'),
                (STEPS[1][0], 'var(--orange)', '2', *STEPS[1][1:], '35% 35%'),
                (STEPS[2][0], 'var(--green)', '3', *STEPS[2][1:], '40% 40%'),
                (STEPS[3][0], 'var(--red)', '4', *STEPS[3][1:], '30% 35%')]),

    minibook=dict(
        cover_title='My Calm<br>Corner', cover_img='in_corner', cover_pos='center 40%',
        cover_lang='<b>ES</b>Mi rincón de calma · <b>KR</b>Kwen kalm mwen',
        pages=[
            ('circle', 'I go to school. I learn with my class.', 'Voy a la escuela. Aprendo con mi clase.', 'Mwen ale lekòl. Mwen aprann ak klas mwen.', 'center 40%'),
            ('tee_overwhelmed', 'Sometimes I get a big feeling. My body feels tight.', 'A veces tengo un sentimiento grande. Mi cuerpo se siente tenso.', 'Pafwa mwen gen yon gwo santiman. Kò m sere.', '30% 30%'),
            ('to_corner', 'I walk to the calm corner. It is okay to go.', 'Camino al rincón de calma. Está bien ir.', 'Mwen mache al nan kwen kalm nan. Li bon pou m ale.', '35% 35%'),
            ('c_breathe', 'I smell the flower. I blow out the candle. Slow, slow, slow.', 'Huelo la flor. Soplo la vela. Lento, lento, lento.', 'Mwen pran sant flè a. Mwen soufle bouji a. Dousman, dousman, dousman.', 'center 30%'),
            (('lee_faces', 'tee_happy'), 'I check my body. Am I calm? Yes!', 'Reviso mi cuerpo. ¿Estoy en calma? ¡Sí!', 'Mwen tcheke kò m. Èske m kalm? Wi!', 'center 30%'),
            ('to_rug', 'I come back to my class. I am ready to learn!', 'Regreso con mi clase. ¡Estoy listo para aprender!', 'Mwen retounen nan klas mwen. Mwen pare pou m aprann!', '30% 35%'),
        ],
        back_img='promise', back_prompt='Color a star when I get calm and come back.'),

    centers=dict(
        sort=dict(title='SORT IT: CALM CORNER OR NOT?', title_size='36px',
                  yes=('✓', 'Calm corner', 'Rincón de calma', 'Kwen kalm'),
                  no=('✋', 'Not for the calm corner', 'No es para el rincón', 'Pa pou kwen kalm nan'),
                  cards=[('c_breathe', 'center 30%'), ('tee_feather', 'center 30%'), ('lee_faces', 'center 30%'), ('lee_breathe', 'center 30%'),
                         ('building', 'center 40%'), ('ball', 'center 40%'), ('nadege_throw', '75% 40%'), ('sofia_scream', 'center 35%')]),
        seq=dict(cards=['tee_overwhelmed', 'to_corner', 'in_corner', 'to_rug'], shuffle=[2, 0, 3, 1]),
        roleplay=dict(prompt='I feel a big feeling. I can...', dirs=[('🃏', 'pick'), ('😟', 'show the feeling'), ('😌', 'show calm')],
                      scenes=[
                          ('tower_falls', 'center 45%', 'My tower falls down.', 'Mi torre se cae.', 'Gwo kay blòk mwen tonbe.'),
                          ('tee_overwhelmed', '30% 30%', 'My work feels too hard.', 'Mi trabajo se siente muy difícil.', 'Travay mwen twò difisil.'),
                          ('lee_sad', 'center 30%', 'I miss my family.', 'Extraño a mi familia.', 'Fanmi m manke m.'),
                          ('lee_worried', 'center 30%', 'It is too loud.', 'Hay demasiado ruido.', 'Gen twòp bri.')]),
        strip=dict(title='DESK STRIPS: MY CALM CORNER STEPS', choices=STEPS,
                   head=('My calm corner steps:', 'Mis pasos del rincón de calma:', 'Etap kwen kalm mwen:')),
        coloring=dict(title='I GET CALM', art='color_calm.png',
                      prompt='Draw your favorite calm tool:',
                      prompt_lang='ES Dibuja tu herramienta de calma favorita. · KR Desine zouti pou kalme ou pi renmen an.'),
    ),

    family=dict(hero='in_corner', hero_pos='center 40%', langs={
        'en': dict(t='Calm Corner', eb='This week in Morning Meeting · Kindergarten to 2nd Grade',
                   intro='Your child is learning to use the calm corner, a cozy spot in the classroom where children go to calm their bodies and then come back to learn. The calm corner is a tool, not a punishment. Big feelings are okay.',
                   sayh='At school we say:', say='The calm corner helps me get calm. Then I come back.', ch='Calm tools', th='Try at home',
                   tips=['<b>Make a calm spot:</b> a pillow or a chair where your child can go to calm down.', '<b>Breathe together:</b> smell the flower, blow out the candle. Three times.', '<b>Name it:</b> “You looked frustrated. You took a break and came back. That was a calm choice!”'],
                   ft='Questions? Talk with your child’s teacher.'),
        'es': dict(t='Rincón de calma', eb='Esta semana en la Reunión de la Mañana · Kínder a 2.º grado',
                   intro='Su hijo o hija está aprendiendo a usar el rincón de calma, un lugar acogedor en el salón donde los niños van a calmar su cuerpo y luego regresan a aprender. El rincón de calma es una herramienta, no un castigo. Está bien tener sentimientos fuertes.',
                   sayh='En la escuela decimos:', say='El rincón de calma me ayuda a calmarme. Luego regreso.', ch='Herramientas de calma', th='Practiquen en casa',
                   tips=['<b>Hagan un lugar de calma:</b> una almohada o una silla donde su hijo o hija pueda calmarse.', '<b>Respiren juntos:</b> huelan la flor, soplen la vela. Tres veces.', '<b>Nómbrelo:</b> “Te veías frustrado. Tomaste un descanso y regresaste. ¡Esa fue una buena decisión!”'],
                   ft='¿Preguntas? Hable con el maestro o la maestra de su hijo o hija.'),
        'kr': dict(t='Kwen kalm', eb='Semèn sa a nan Reyinyon Maten · Kindègadenn rive 2yèm ane',
                   intro='Pitit ou ap aprann sèvi ak kwen kalm nan, yon ti kote ki konfòtab nan klas la kote timoun yo ale pou kalme kò yo, epi apre sa yo retounen pou yo aprann. Kwen kalm nan se yon zouti, se pa yon pinisyon. Li nòmal pou yon timoun santi gwo santiman.',
                   sayh='Nan lekòl la nou di:', say='Kwen kalm nan ede m kalme m. Apre sa, mwen retounen.', ch='Zouti pou kalme', th='Eseye lakay ou',
                   tips=['<b>Fè yon kote pou kalme:</b> yon zòrye oswa yon chèz kote pitit ou ka al kalme l.', '<b>Respire ansanm:</b> pran sant flè a, soufle bouji a. Twa fwa.', '<b>Di l:</b> “Ou te sanble fristre. Ou te pran yon ti repo epi ou retounen. Se te yon bon chwa!”'],
                   ft='Ou gen kesyon? Pale ak pwofesè pitit ou a.'),
    }),

    guide=dict(
        images=[('in_corner', 300, 168), ('to_rug', 300, 168)],
        glance=[
            ('Goal', 'Students follow the four calm corner steps (notice, walk, get calm, come back) and say “The calm corner helps me get calm. Then I come back.”'),
            ('Time', '15 minutes in Morning Meeting, in place of the general lesson. Centers run during the week.'),
            ('When', 'Teach early in the year and again after any long break. Teach it before the calm corner is needed, at a calm time.'),
            ('In the bundle', 'Student deck (7 slides, press N for notes) · Poster (letter and 11×17) · Center kit (sort, sequence, act it out, desk strips, coloring) · Mini book · Family half-sheet'),
            ('Words we use', '“Big feelings are okay.” · “The calm corner helps me get calm. Then I come back.” · “I notice. I walk. I get calm. I come back.”'),
        ],
        before=[
            'Set up the calm corner before the lesson: a soft seat, the breathing pictures, and the feelings faces. Fidgets are not part of this routine.',
            'Hang the poster inside or right next to the calm corner. Students point to the steps all week.',
            'The calm corner is a tool, not a time-out. Never send a student there as a consequence, and never call it “time-out” or “the thinking spot.”',
            'One friend in the calm corner at a time. Most students are ready to come back in about 3 to 5 minutes. If a student stays longer, check in quietly.',
            'Pair students who need support with a steady turn-and-talk partner before the lesson starts.',
        ],
        slides=[
            ('1 · Title & Promise (R2)', 'Point to your calm corner. “This is our calm corner. Everyone gets big feelings. Today we learn how the calm corner helps us get calm and come back.” Say together: “Big feelings are okay.”', 'Eyes on the slide or the real corner; students repeat the line.', 'Equity stick: “Point to our calm corner.” Pointing is a full answer.'),
            ('2 · Get Calm First (R1)', 'Do it with them. “Smell the flower. Blow out the candle. Long and slow. Three times.” Tell them it is one of the calm corner tools.', 'Exhale longer than inhale; shoulders drop.', 'LiveSchool point: “You breathed slow three times.”'),
            ('3 · What Did Tee Do? (R2, R3)', 'Point to each picture. “The work felt too hard. Tee got a big feeling. He walked to the calm corner. He got calm. Then he came back to the rug.” Class says: “The calm corner helps me get calm. Then I come back.”', 'Students follow the pictures; whole class repeats the line.', 'Equity stick: “Which picture shows Tee getting calm? Point.”'),
            ('4 · Turn and Talk (R3, R4)', 'Model knee to knee. “Look at Tee. Tell your partner: Tee feels ___.” 30 seconds, then ring back.', 'Partners take turns; worried and frustrated are both right.', 'Equity stick: two shares. Praise the full sentence.'),
            ('5 · Watch Me, Then Show Me (R3, R4, R5)', 'Read: “My tower falls down. I feel a big feeling. I…” A student models the four steps at your real calm corner, including coming back. Ask, “What did they do first? Last?” Then everyone practices the steps in place.', 'A student models all four steps; class names them in order.', 'LiveSchool point for the student model. Name the come-back step out loud.'),
            ('6 · My Promise Today (R2, R5)', 'Hand on heart. “Say it with me: I get calm. I come back.” Then: “Point to the calm tool you will use.”', 'Every student says the promise and points to one tool.', 'Equity stick: three names. Pointing counts.'),
            ('7 · How We Leave (R1, R4, R5)', '“Stand up. Calm body. Walk. Ready to learn.” Do not time this at K–2.', 'Calm bodies while moving; calm walking.', 'LiveSchool point for the table that walks with calm bodies the whole way.'),
        ],
        bridges=[
            ('Excellent', '“Show the class again. Everyone, what was the last step?” Then the whole class does the steps together.'),
            ('Partly right', '“You got calm. Now show us the last step: come back. Try again.”'),
            ('Silly', '“Thank you. Let’s see it the calm way.” Call a new student. No commentary.'),
        ],
        centers=[
            ('Sort It', 'Sort mat (landscape page) and 8 cut picture cards.', '“Look at each picture. Is it something we do in the calm corner? Put it on the side where it goes.”', '4 cards on Calm corner, 4 on Not for the calm corner.'),
            ('Put It in Order', 'Sequencing mat and 4 cut cards.', '“Put the pictures in order: first, next, then, last. Tell your partner the story.”', 'Students retell: big feeling, walk, get calm, come back.'),
            ('Act It Out', '4 role-play cards in a stack.', '“Pick a card. Read it with me. Show the feeling. Then show a calm tool from the pictures.”', 'Each student shows one calm tool.'),
            ('Calm Corner Steps', 'Desk strips, one per student.', '“Point to each step and say it with me: notice, walk, get calm, come back.”', 'Each student points to all four steps in order.'),
            ('Color', 'Coloring page and crayons.', '“Color Tee getting calm. In the box, draw your favorite calm tool.”', 'A drawing of a calm tool, like breathing or resting.'),
        ],
        keys=[
            ('Sort, Calm corner: ', 'Tee smelling and blowing · Tee doing feather breath · Lee’s feelings faces · Lee sitting and resting.'),
            ('Sort, Not for the calm corner: ', 'friends building with blocks · Tee and Malik playing ball · Nadege about to throw a block · Sofia screaming.'),
            ('Put It in Order: ', '1 Tee has a big feeling at his table · 2 Tee walks to the calm corner · 3 Tee gets calm in the corner · 4 Tee walks back to the rug.'),
        ],
        minibook=[
            'For a child who needs extra practice using the calm corner: one who avoids it, stays a long time, or has trouble coming back.',
            'Read it one-on-one at a calm time, then walk to the real calm corner together and practice the steps.',
            'Read it every day for a week. Let the child turn the pages and act out each step.',
            'On the back, the child colors a star each day they get calm and come back. Celebrate every star.',
        ],
        when_title='When the calm corner gets tricky',
        when_intro='Follows the Responsive Behavior Plan: the adult response is the intervention. Fewer words as escalation rises.',
        when=[
            ('A student needs the corner but does not go. ', 'Offer, do not order: “Do you want to go to the calm corner or breathe here with me?” Two choices, then wait.'),
            ('A student plays in the corner. ', 'Quietly: “The calm corner is for getting calm. Show me a calm tool.” If play continues, the student returns to the group and tries again later.'),
            ('A student does not come back. ', 'After about 5 minutes, kneel and check in: “Is your body calm? Show me thumbs up when you are ready.” Then walk back together.'),
            ('Two students want the corner at once. ', 'One friend at a time. The second student breathes at their seat with the desk strip, then gets the next turn.'),
            ('A student uses the corner to leave every task. ', 'Note it on the Live Card and talk with your coach and the counseling team. The calm corner is still never taken away.'),
            ('Unsafe in the corner. ', 'If a student is unsafe to self or others, follow the Responsive Behavior Plan and call for support.'),
        ],
        when_outro='Next in the toolkit: Topic 3, Belly Breathing, and Topic 4, Asking for a Break.',
    ),

    site=dict(card_img='in_corner', line='I can use the calm corner, get calm, and come back.',
              hero_img='in_corner', hero_alt='Tee resting calmly in the calm corner', hero_pos='center 40%',
              story_desc='Get calm, watch Tee use the calm corner, turn and talk, practice the four steps, make a promise, and leave calmly.',
              centers_desc='Sort mat and 8 picture cards, sequencing mat and cards, role-play cards, calm corner step strips, and a coloring page.',
              minibook_desc='A read-together story for students who need more practice getting calm and coming back. Read it one on one, then practice at the real calm corner.',
              guide_desc='The lesson at a glance, the slide-by-slide script, how to run the centers, and what to do when the calm corner gets tricky.',
              family_desc='What the calm corner is, what we say at school, and three things to try at home. One page per language, two half-sheets per page.',
              poster_hint='Hang it inside or right next to your calm corner.'),
)
