# Topic 3 · Belly Breathing (draft 1; not published). Build: python3 build.py topics/03-belly-breathing.py
# Tee leads this story (Lee led Topic 1). Skill: balloon belly breath, hand on belly, in slow (belly big),
# out slow (belly small), three times. Calm-corner tools only, no fidgets.
# New Flow art: bb_hero, bb_busy, bb_belly, bb_blow, bb_calm (classroom) and bb_s1..bb_s4 (Tee, white background).

STEPS = [  # (art, EN, ES, KR): the four steps of a belly breath
    ('bb_s1', 'Hand on belly', 'Mano en la barriga', 'Men sou vant'),
    ('bb_s2', 'Breathe in: belly big', 'Inhalo: barriga grande', 'Respire antre: vant gonfle'),
    ('bb_s3', 'Breathe out: belly small', 'Exhalo: barriga pequeña', 'Respire soti: vant desann'),
    ('bb_s4', 'My body is calm', 'Mi cuerpo está tranquilo', 'Kò m kalm'),
]

TOPIC = dict(
    num=3,
    slug='03-belly-breathing',
    file_prefix='Belly-Breathing',
    deck_slug='belly-breathing',
    title='Belly Breathing',
    full_title='Belly Breathing',
    title_lines=['BELLY', 'BREATHING'],
    subtitle='I can breathe slow to calm my body',
    value='Responsible',
    part='Skills I can use',
    promise=dict(
        en='I can breathe slow to calm my body.',
        es='Puedo respirar despacio para calmar mi cuerpo.',
        kr='Mwen ka respire dousman pou m kalme kò m.',
    ),
    card_line='I can breathe slow to calm my body.',
    song=None,
    choices=STEPS,
    choices_head=dict(en='My belly breath', es='Mi respiración de barriga', kr='Respirasyon vant mwen'),
    deck=dict(
        eyebrow='Morning Meeting · Responsible',
        s1=dict(bubble='My belly is a balloon!', words='breathe · respirar · respire', img='bb_hero', pos='center 30%'),
        s2=dict(img='class_breathe', pos='center 35%'),
        s3=dict(
            title='WHAT DID TEE DO?',
            layout='grid',
            panels=[
                dict(img='bb_busy', pos='center', num='1', label='Busy body.', color='var(--sky)'),
                dict(img='bb_belly', pos='center', num='2', label='Breathe in.', color='var(--orange)'),
                dict(img='bb_blow', pos='center', num='3', label='Breathe out.', color='var(--green)'),
                dict(img='bb_calm', pos='center', num='4', label='Calm body.', color='var(--red)'),
            ],
            say='Hand on belly. Breathe in slow. Breathe out slow. Three times.',
        ),
        s4=dict(
            title='WHAT CAN TEE DO?',
            img='bb_busy',
            pos='center 35%',
            stem='Tee can ___.',
            face_pos='center 35%',
            faces=[('bb_s2', 'belly breathe'), ('c_corner', 'calm corner'), ('c_grownup', 'ask for help')],
        ),
        s5=dict(
            title='BALLOON BELLY',
            img='bb_belly',
            pos='center 35%',
            q='Hand on your belly.',
            q2='In... and out.',
            choice_fit='contain',
            choices=[(k, en) for k, en, es, kr in STEPS],
        ),
        s6=dict(
            vow='I can breathe slow<br>to calm my body.',
            stem='When my body feels busy, I can ___.',
            choice_pos='center 35%',
            choices=[('bb_s2', 'belly breathe'), ('c_corner', 'calm corner'), ('c_grownup', 'ask for help')],
            img='promise',
        ),
        s7=dict(
            steps=[('🧍', 'Stand up'), ('🎈', 'Calm body'), ('👣', 'Walk'), ('⭐', 'Ready to learn')],
            pill='My body is calm!',
            img='leave',
        ),
        notes=[
            dict(
                name='Title &amp; Promise',
                rubric='R2',
                script='Put one hand on your belly. “Our belly can be like a balloon. When we breathe in slow, it gets big. When we breathe out slow, it gets small. Slow breaths help our body feel calm.” Say together: “My belly is a balloon!”',
                look=['Eyes on the slide or on you', 'Hands on bellies', 'Students repeat the line'],
                breaks=['If students puff their cheeks or blow loudly: “Slow and quiet. Like a balloon floating, not popping.” Model once and move on.'],
                support=['Sit beside any student who has had a hard morning'],
                language=['Touch your belly as you say “belly”', 'Spanish: barriga, respirar · Kreyòl: vant, respire'],
                move='Equity stick: pull one name. “Show me where your belly is.” Pointing is a full answer.',
                aside='Belly breathing is a body skill. Students learn it best when they are already calm, so practice it every day, not only when someone is upset.',
            ),
            dict(
                name='Regulate · Get Calm First',
                rubric='R1',
                script='Model the gesture with them every time. “Smell the flower. Blow out the candle. Long and slow. Three times.” Do it with the class, not from the front.',
                look=['Exhale longer than inhale', 'Shoulders drop', 'Gesture copied'],
                breaks=['If silliness: model silently once, then invite them back.'],
                support=['Breathe audibly beside any student who cannot settle'],
                language=['No language demand; gesture carries it', 'Same two gestures used in every K–2 lesson'],
                move='LiveSchool: award a point to a student who breathes all three times with you. Name the behavior: “You breathed slow three times.”',
                aside='Tell the class: “Today we learn one more way to breathe slow. It lives in our belly.”',
            ),
            dict(
                name='Orient · The Story',
                rubric='R2, R3',
                script='Point to each picture as you tell it. “It was clean-up time, but Tee’s drawing was not done. His heart went fast. His shoulders got tight. His breath got short and quick. Tee put his hand on his belly. He breathed in slow, and his belly got big, like a balloon. He breathed out slow, and his belly got small. He did it three times. His body felt calm. Then he asked, ‘Can I finish my drawing later?’ His teacher said, ‘Yes. Thank you for asking calmly.’” Then have the class say together: “Hand on belly. Breathe in slow. Breathe out slow. Three times.”',
                look=['Students follow the pictures in order', 'Whole class repeats the We say line'],
                breaks=['If students giggle at “belly”: smile and keep going. “Yes, belly! Everyone has one.”'],
                support=['Point to each panel as the teacher narrates'],
                language=['Four pictures, two words each; numbers carry the order', 'Show “busy body” by lifting your shoulders up tight, then dropping them'],
                move='Equity stick: “Which picture shows Tee’s belly getting big? Point.” Pointing is a full answer.',
                aside='Tee did not have to stop feeling upset. He calmed his body first. Then he could use his words.',
            ),
            dict(
                name='Connect · Turn and Talk',
                rubric='R3, R4',
                script='Show knee to knee with a student partner. “Turn knee to knee. Look at Tee. His body feels busy. Tell your partner: Tee can ___.” Give 30 seconds, then ring back. Ask one pair: “What did your partner say?”',
                look=['Partners face each other', 'Students name belly breathing or point to a picture', 'Some students name another calm tool'],
                breaks=['If a pair is stuck: kneel in and say the stem with them.', 'If partners argue: “Take turns. You go first, then you.”'],
                support=['Pair any student who needs support with a steady partner before the lesson starts'],
                language=['Pointing to a picture is a complete answer', 'Spanish: “Tee puede respirar despacio” · Kreyòl: “Tee ka respire dousman”'],
                move='Equity stick: call two names to share. Every calm tool on the slide is a right answer.',
                aside='All three pictures are good choices. Belly breathing is the one we practice today.',
            ),
            dict(
                name='Practice · Watch Me, Then Show Me',
                rubric='R3, R4, R5',
                script='Invite one student to the front to model with you. “Hand on belly. Breathe in through your nose, slow, slow, slow. Feel your belly get big. Now breathe out slow, like you are blowing a balloon away. Feel your belly get small.” The student model does it once while the class watches. Then the whole class does three belly breaths together, counting with fingers: one, two, three.',
                look=['Hands on bellies', 'Bellies move out on the breath in', 'Breath out is slow and quiet'],
                breaks=['Excellent model: “Show us again. Everyone, watch the hand on the belly move.”', 'Partly right model: “Your breath was slow. Now put your hand on your belly so you can feel it.”', 'Silly model: “Thank you. Let’s see it the calm way.” Call a new student; no commentary.'],
                support=['Kneel beside a student who lifts their shoulders instead of their belly. Place your own hand on your belly and breathe together.'],
                language=['Four step pictures with words; students can point instead of naming', 'Spanish: Inhalo, exhalo · Kreyòl: Respire antre, respire soti'],
                move='LiveSchool: award the student model a point. Name it out loud: “You breathed slow, and your belly got big.”',
                aside='If a student does not feel their belly move, have them lie on their back later with a stuffed animal on their belly and watch it ride up and down.',
            ),
            dict(
                name='Commit · My Promise Today',
                rubric='R2, R5',
                script='Put your hand on your heart. “Say it with me: I can breathe slow to calm my body.” Then: “When your body feels busy, what can you do? Point to one.” Model it first: “I can belly breathe.”',
                look=['Every student says the promise', 'Every student points to one picture'],
                breaks=['If a student does not choose: offer two pictures and let them point.'],
                support=['Remind any student who points to the calm corner that belly breathing works there too'],
                language=['Hand on heart carries the promise', 'Spanish: Puedo respirar despacio · Kreyòl: Mwen ka respire dousman'],
                move='Equity stick: pull three names: “Which one did you point to?” Pointing counts.',
                aside='',
            ),
            dict(
                name='Transition · How We Leave',
                rubric='R1, R4, R5',
                script='“How we leave is how we start our learning. One belly breath first. Now: stand up. Calm body. Walk. Ready to learn.” Do not time this at K–2.',
                look=['Calm bodies while moving', 'Calm walking, not rushing'],
                breaks=['“Let’s try that again. Back to your spot.” Rebuild clean, no commentary on individuals.'],
                support=['Stand at the destination, not behind the group'],
                language=['Four icons, four words', 'No timing pressure at this age'],
                move='LiveSchool: award a point to the table that walks with calm bodies the whole way.',
                aside='Use one belly breath before every transition this week. Say: “Balloon belly, then we move.”',
            ),
        ],
    ),
    poster=dict(
        header_img='bb_hero',
        footer_img='thumbs',
        choice_fit='contain',
        panels=[
            dict(img='bb_busy', pos='center', color='var(--sky)', symbol='1', en='My body feels busy. My breath is fast.', es='Mi cuerpo se siente agitado. Respiro rápido.', kr='Kò m ajite. M ap respire vit.'),
            dict(img='bb_belly', pos='center', color='var(--orange)', symbol='2', en='Hand on belly. Breathe in slow. My belly gets big.', es='Mano en la barriga. Inhalo despacio. Mi barriga se hace grande.', kr='Men sou vant. M respire antre dousman. Vant mwen gonfle.'),
            dict(img='bb_blow', pos='center', color='var(--green)', symbol='3', en='Breathe out slow. My belly gets small.', es='Exhalo despacio. Mi barriga se hace pequeña.', kr='M respire soti dousman. Vant mwen desann.'),
            dict(img='bb_calm', pos='center', color='var(--red)', symbol='4', en='Three times. My body feels calm.', es='Tres veces. Mi cuerpo se siente tranquilo.', kr='Twa fwa. Kò m santi l kalm.'),
        ],
    ),
    minibook=dict(
        cover_title='Belly<br>Breathing',
        cover_img='bb_hero',
        cover_pos='center 30%',
        cover_es='Respiro con la barriga',
        cover_kr='M respire ak vant mwen',
        pages=[
            dict(img='bb_busy', pos='center', en='Sometimes my body feels busy. My breath goes fast.', es='A veces mi cuerpo se siente agitado. Respiro rápido.', kr='Pafwa kò m ajite. M ap respire vit.'),
            dict(img='bb_s1', pos='center 30%', fit='contain', en='I put my hand on my belly.', es='Pongo la mano en mi barriga.', kr='Mwen mete men m sou vant mwen.'),
            dict(img='bb_s2', pos='center 30%', fit='contain', en='I breathe in slow. My belly gets big, like a balloon.', es='Inhalo despacio. Mi barriga se hace grande, como un globo.', kr='Mwen respire antre dousman. Vant mwen gonfle tankou yon balon.'),
            dict(img='bb_s3', pos='center 30%', fit='contain', en='I breathe out slow. My belly gets small.', es='Exhalo despacio. Mi barriga se hace pequeña.', kr='Mwen respire soti dousman. Vant mwen desann.'),
            dict(img='bb_s4', pos='center 30%', fit='contain', en='I do it three times. In... and out.', es='Lo hago tres veces. Inhalo... y exhalo.', kr='Mwen fè l twa fwa. Antre... epi soti.'),
            dict(img='bb_calm', pos='center', en='My body feels calm. I am ready.', es='Mi cuerpo se siente tranquilo. Estoy en calma.', kr='Kò m kalm. Mwen pare.'),
        ],
        back_img='promise',
        back_prompt='Color a star each time I belly breathe.',
    ),
    centers=dict(
        sort=dict(
            title='SORT IT: CALM BODY OR BUSY BODY?',
            yes=dict(symbol='🎈', en='Calm body', es='Cuerpo tranquilo', kr='Kò kalm'),
            no=dict(symbol='💨', en='Busy body: time to breathe', es='Cuerpo agitado: a respirar', kr='Kò ajite: lè pou m respire'),
            cards=[
                ('class_breathe', 'center 35%', 'yes'),
                ('cc_run', 'center 40%', 'no'),
                ('cc_book', 'center 40%', 'yes'),
                ('sofia_scream', 'center 35%', 'no'),
                ('in_corner', 'center 40%', 'yes'),
                ('tee_overwhelmed', '30% 30%', 'no'),
                ('cc_breathe', 'center 40%', 'yes'),
                ('cc_jump', 'center 35%', 'no'),
            ],
        ),
        seq=dict(
            cards=[
                ('bb_busy', 'Busy body'),
                ('bb_belly', 'Breathe in'),
                ('bb_blow', 'Breathe out'),
                ('bb_calm', 'Calm body'),
            ],
            print_order=[2, 0, 3, 1],
        ),
        roleplay=dict(
            prompt='Belly breathe!',
            dirs=[('🃏', 'pick'), ('✋', 'hand on belly'), ('🎈', 'breathe 3 times')],
            scenes=[
                ('bb_busy', 'center', 'It is clean-up time and I am not done.', 'Es hora de recoger y no he terminado.', 'Se lè pou n ranje e m poko fini.'),
                ('tower_falls', 'center 45%', 'My tower falls down.', 'Mi torre se cae.', 'Gwo kay blòk mwen tonbe.'),
                ('ff_worried', 'center 35%', 'It is my turn to read out loud.', 'Me toca leer en voz alta.', 'Se tou pa m pou m li fò.'),
                ('cc_crowd', 'center 40%', 'The calm corner is busy.', 'El rincón de calma está ocupado.', 'Kwen kalm nan gen moun ladan l.'),
            ],
        ),
        strips=dict(
            title='DESK STRIPS: MY BELLY BREATH',
            choices=STEPS,
            head=dict(en='Belly breath:', es='Respiración de barriga:', kr='Respirasyon vant:'),
        ),
        color=dict(
            title='MY BALLOON BELLY',
            trace='bb_s2',
            trace_opts=dict(blur=1.2, thicken=1),
            prompt='Color Tee. Then put your hand on your belly and breathe with him.',
            prompt_es='Colorea a Tee. Luego pon la mano en tu barriga y respira con él.',
            prompt_kr='Kolore Tee. Apre sa, mete men w sou vant ou epi respire avè l.',
        ),
    ),
    family=dict(
        hero='bb_hero',
        hero_pos='center 30%',
        en=dict(
            t='Belly Breathing',
            eb='This week in Morning Meeting · Kindergarten to 2nd Grade',
            intro='Your child is learning belly breathing: a hand on the belly, a slow breath in so the belly gets big like a balloon, and a slow breath out so it gets small. Three slow belly breaths help a busy body feel calm.',
            sayh='At school we say:',
            say='Hand on belly. Breathe in slow. Breathe out slow. Three times.',
            ch='The four steps',
            th='Try at home',
            tips=[
                '<b>Breathe together:</b> at bedtime, lie down and put a stuffed animal on your child’s belly. Watch it go up and down.',
                '<b>Practice when calm:</b> try three belly breaths before school or dinner, so it is easy to use when your child is upset.',
                '<b>Breathe first:</b> when you feel rushed, say, “I am going to belly breathe,” and do it. Children learn by watching you.',
            ],
            ft='Questions? Talk with your child’s teacher.',
        ),
        es=dict(
            t='Respiro con la barriga',
            eb='Esta semana en la Reunión de la Mañana · Kínder a 2.º grado',
            intro='Su hijo o hija está aprendiendo a respirar con la barriga: la mano en la barriga, inhalar despacio para que se haga grande como un globo y exhalar despacio para que se haga pequeña. Tres respiraciones lentas calman el cuerpo.',
            sayh='En la escuela decimos:',
            say='Mano en la barriga. Inhalo despacio. Exhalo despacio. Tres veces.',
            ch='Los cuatro pasos',
            th='Practiquen en casa',
            tips=[
                '<b>Respiren juntos:</b> a la hora de dormir, pongan un peluche sobre la barriga y miren cómo sube y baja.',
                '<b>Practiquen en calma:</b> hagan tres respiraciones antes de la escuela o la cena.',
                '<b>Respire primero:</b> cuando tenga prisa, diga: “Voy a respirar con la barriga,” y hágalo. Los niños aprenden de usted.',
            ],
            ft='¿Preguntas? Hable con el maestro o la maestra de su hijo o hija.',
        ),
        kr=dict(
            t='M respire ak vant mwen',
            eb='Semèn sa a nan Reyinyon Maten · Kindègadenn rive 2yèm ane',
            intro='Pitit ou ap aprann respire ak vant li: men sou vant, respire antre dousman pou vant lan gonfle tankou yon balon, epi respire soti dousman pou l desann. Twa respirasyon dousman ede yon kò ajite vin kalm.',
            sayh='Nan lekòl la nou di:',
            say='Men sou vant. Respire antre dousman. Respire soti dousman. Twa fwa.',
            ch='Kat etap yo',
            th='Eseye lakay ou',
            tips=[
                '<b>Respire ansanm:</b> lè pou dòmi, mete yon ti bèt an twal sou vant pitit ou. Gade l monte epi desann.',
                '<b>Pratike lè l kalm:</b> fè twa respirasyon anvan lekòl oswa anvan manje.',
                '<b>Respire anvan:</b> lè ou prese, di: “Mwen pral respire ak vant mwen,” epi fè l. Timoun yo aprann lè yo gade ou.',
            ],
            ft='Ou gen kesyon? Pale ak pwofesè pitit ou a.',
        ),
    ),
    guide=dict(
        images=[('bb_busy', 300, 168), ('bb_calm', 300, 168)],
        glance=[
            ('Goal', 'Students use a belly breath (hand on belly, slow breath in, slow breath out, three times) to calm a busy body.'),
            ('Time', '15 minutes in Morning Meeting, in place of the general lesson. Centers run during the week.'),
            ('When', 'Teach after Topic 1, Naming My Feelings, and Topic 2, Using the Calm Corner. Belly breathing is a tool students use in the calm corner.'),
            ('In the bundle', 'Student deck (7 slides, press N for notes) · Poster (letter and 11×17) · Center kit (sort, sequence, act it out, desk strips, coloring) · Mini book · Family half-sheet'),
            ('Words we use', '“My belly is a balloon.” · “Hand on belly. Breathe in slow. Breathe out slow. Three times.” · “Busy body” and “calm body”'),
        ],
        before=[
            'Hang the poster at child height near your meeting space or the calm corner. Students point to it all week.',
            'Practice belly breathing when students are already calm. A skill practiced in calm moments is easier to use in hard ones.',
            'Say “busy body” and “calm body.” A busy body is not a bad body; it is a signal to breathe.',
            'Tape a desk strip at the table of any student who needs the steps close by.',
            'Pair students who need support with a steady turn-and-talk partner before the lesson starts.',
        ],
        slides=[
            ('1 · Title & Promise (R2)', 'Hand on your belly. “Our belly can be like a balloon. Breathe in slow, it gets big. Breathe out slow, it gets small.” Say together: “My belly is a balloon!”', 'Hands on bellies; students repeat the line.', 'Equity stick: “Show me where your belly is.”'),
            ('2 · Get Calm First (R1)', 'Do it with them. “Smell the flower. Blow out the candle. Long and slow. Three times.”', 'Exhale longer than inhale; shoulders drop.', 'LiveSchool point: “You breathed slow three times.”'),
            ('3 · What Did Tee Do? (R2, R3)', 'Point to each picture. “It was clean-up time, but Tee’s drawing was not done. His breath got fast. He put his hand on his belly, breathed in slow, breathed out slow, three times. His body felt calm, and he asked, ‘Can I finish later?’” Class says: “Hand on belly. Breathe in slow. Breathe out slow. Three times.”', 'Students follow the pictures; whole class repeats the line.', 'Equity stick: “Which picture shows Tee’s belly getting big? Point.”'),
            ('4 · Turn and Talk (R3, R4)', 'Model knee to knee. “Tee’s body feels busy. Tell your partner: Tee can ___.” 30 seconds, then two shares.', 'Partners take turns; any calm tool on the slide is right.', 'Equity stick: two shares.'),
            ('5 · Watch Me, Then Show Me (R3, R4, R5)', 'A student models one belly breath with you while the class watches. Then the whole class does three together, counting on fingers.', 'Hands on bellies; bellies move out on the breath in; quiet, slow breath out.', 'LiveSchool point for the student model.'),
            ('6 · My Promise Today (R2, R5)', 'Hand on heart. “Say it with me: I can breathe slow to calm my body.” Then: “When your body feels busy, point to one.”', 'Every student says the promise and points to one picture.', 'Equity stick: three names. Pointing counts.'),
            ('7 · How We Leave (R1, R4, R5)', 'One belly breath first. “Stand up. Calm body. Walk. Ready to learn.” Do not time this at K–2.', 'Calm bodies while moving; calm walking.', 'LiveSchool point for the table that walks with calm bodies the whole way.'),
        ],
        bridges=[
            ('Excellent', '“Show us again. Everyone, watch the hand on the belly move.”'),
            ('Partly right', '“Your breath was slow. Now put your hand on your belly so you can feel it.”'),
            ('Silly', '“Thank you. Let’s see it the calm way.” Call a new student. No commentary.'),
        ],
        centers=[
            ('Sort It', 'Sort mat (landscape page) and 8 cut picture cards.', '“Look at each picture. Is it a calm body or a busy body? Put it on the side where it goes.”', '4 cards on Calm body, 4 on Busy body. Accept any sort a student can explain.'),
            ('Put It in Order', 'Sequencing mat and 4 cut cards.', '“Put Tee’s story in order: first, next, then, last. Tell your partner the story.”', 'Students retell: busy body, breathe in, breathe out, calm body.'),
            ('Act It Out', '4 role-play cards in a stack.', '“Pick a card. Read it with me. Hand on belly. Breathe three times.”', 'Each student does three belly breaths for a card.'),
            ('Belly Breath Steps', 'Desk strips, one per student.', '“Point to each step and do it.”', 'Each student does all four steps.'),
            ('Color', 'Coloring page and crayons.', '“Color Tee. Then put your hand on your belly and breathe with him.”', 'A colored page and three belly breaths.'),
        ],
        keys=[
            ('Sort, Calm body: ', 'Lee and Tee breathing on the rug · Lee reading in the calm corner · Tee resting in the calm corner · Lee breathing in the calm corner.'),
            ('Sort, Busy body: ', 'a friend running · Sofia screaming · Tee finds the work too hard · a friend jumping in the calm corner.'),
            ('Put It in Order: ', '1 Tee’s body feels busy at clean-up time · 2 Tee breathes in, belly big · 3 Tee breathes out, belly small · 4 Tee is calm and asks to finish later.'),
        ],
        minibook=[
            'For a child who needs extra practice calming their body: one whose breath gets fast and shoulders get tight, or who has trouble settling after transitions.',
            'Read it one-on-one at a calm time. Do each step together as you read it.',
            'Read it every day for a week. Let the child turn the pages and lead the breaths.',
            'On the back, the child colors a star each time they belly breathe. Celebrate every star.',
        ],
        when_title='When belly breathing gets tricky',
        when_intro='Follows the Responsive Behavior Plan: the adult response is the intervention. Fewer words as escalation rises.',
        when=[
            ('A student breathes fast or gets dizzy. ', 'Slow it down: “Smaller breath. Slow, slow.” Breathing should feel easy, never forced.'),
            ('A student lifts their shoulders, not their belly. ', 'Have them lie down with a stuffed animal on their belly and watch it rise.'),
            ('A student is too upset to try. ', 'Do not teach in the moment. Breathe slowly beside them so they can hear you. Offer the calm corner.'),
            ('A student refuses. ', 'No power struggle. “You can watch me.” Breathe yourself. Try again later when they are calm.'),
            ('A student is unsafe. ', 'Safety first. Use Topic 7, Gentle Hands, and the Responsive Behavior Plan.'),
        ],
        when_outro='Next in the toolkit: Topic 4, Asking for a Break.',
    ),
    site=dict(
        hero_img='bb_hero',
        hero_alt='Lee and Tee belly breathing with hands on their bellies',
        hero_pos='center 30%',
        deck_desc='Get calm, watch Tee belly breathe, turn and talk, practice balloon belly breaths together, make a promise, and leave calmly.',
        guide_desc='The lesson at a glance, the slide-by-slide script, how to run the centers, and what to do when belly breathing gets tricky.',
        poster_hint='Hang it at child height near your meeting space or the calm corner.',
        centers_desc='Sort mat and 8 picture cards, sequencing mat and cards, role-play cards, belly breath step strips, and a coloring page.',
        minibook_desc='A read-together book for students who need more practice calming their body. Do each step together as you read.',
        family_desc='What your child is learning, what we say at school, and three ways to belly breathe at home. One page per language, two half-sheets per page.',
    ),
)
