# Topic 7 · Gentle Hands with Friends (Set 1, published 2026-10-07)
CHOICES = [  # (art, EN, ES, KR) : the calm choices used across the bundle
    ('c_corner', 'Go to the calm corner', 'Ir al rincón de calma', 'Ale nan kwen kalm nan'),
    ('c_breathe', 'Take deep breaths', 'Respirar profundo', 'Respire fon'),
    ('c_break', 'Ask for a break', 'Pedir un descanso', 'Mande yon ti repo'),
    ('c_words', 'Use my words', 'Usar mis palabras', 'Sèvi ak pawòl mwen'),
    ('c_grownup', 'Ask a grown-up', 'Pedir ayuda a un adulto', 'Mande yon granmoun èd'),
]

TOPIC = dict(
    num=7, folder='07-gentle-hands', slug='gentle-hands', prefix='Gentle-Hands',
    zip_slug='gentle-hands-with-friends', zip_folder='Gentle-Hands-with-Friends',
    title='Gentle Hands with Friends', short='Gentle Hands', part='Safe choices', value='Safe',
    title_lines=['GENTLE', 'HANDS'], sub='with my friends',
    promise=('I use gentle hands. I keep my friends safe.', 'Uso manos suaves. Cuido a mis amigos.',
             'Mwen sèvi ak men dous. Mwen pwoteje zanmi m yo.'),
    song=dict(file='../../resources/k2-behavior-toolkit/07-gentle-hands/gentle-hands-song.mp4', length='about 1 minute 24 seconds',
              poster_at=2.5),
    choices=CHOICES,
    choices_head=('When I feel mad, I can:', 'Cuando me enojo, puedo:', 'Lè m fache, mwen ka:'),

    deck=dict(
        s1=dict(eyebrow='Morning Meeting · Safe', bubble='Our hands keep our friends safe!',
                words='gentle · suave · dous', img='welcome', pos='center 20%'),
        s2=dict(img='calm', pos='center 30%'),
        s3=dict(panels=[('malik_fists', 'Mad!', 'var(--red)', '68% 40%'), ('nadege_hurt', 'Ouch.', 'var(--sky)', '40% 35%'),
                        ('high_five', 'Gentle hands.', 'var(--green)', 'center 15%'), ('building', 'Safe and fun!', 'var(--orange)', 'center 40%')],
                say='Hitting hurts. We use gentle hands.'),
        s4=dict(title='HOW DOES SHE FEEL?', img='nadege_hurt', pos='center 35%', stem='She feels ___.',
                faces=[('lee_happy', 'happy'), ('lee_sad', 'sad'), ('lee_mad', 'mad')]),
        s5=dict(title='WHEN I FEEL MAD, I CAN', img='malik_fists', pos='center 40%',
                q='A friend takes my truck.', q2='I feel mad. I can...', choices=[0, 1, 2, 3, 4]),
        s6=dict(vow='I use gentle hands.', stem='When I feel mad, I will ___.', choices=[1, 0, 4], img='promise'),
        s7=dict(steps=[('🧍', 'Stand up'), ('🤲', 'Gentle hands'), ('👣', 'Walk'), ('⭐', 'Ready to learn')],
                pill='Gentle hands all day!', img='leave'),
        notes=[
            ('Title &amp; Promise', 'R2',
             'Hold up both open hands, palms out, and wiggle the fingers. “These are my hands. Today we learn how our hands keep our friends safe. Show me your hands.” Wait until every hand is up before moving on.',
             ['Every student shows open hands', 'Eyes on the slide or on you'],
             ['Silly hands: model again, slowly and silently, then invite them back. No lecture.'],
             ['Sit beside any student who has had a hard morning; keep this lesson warm, not corrective'],
             ['“Gentle” is new for many students: say it while softly patting your own arm', 'Spanish: suave · Kreyòl: dous'],
             'Equity stick: pull one name and ask, “Show me gentle hands.” Any calm open hands earns praise.',
             'Tier note: teach this before trouble, not the morning after a hitting incident in this room. If a child was hit today, wait a day. Never cast a real student as the child in the story.'),
            ('Regulate · Get Calm First', 'R1',
             'Model the gesture with them every time. “Smell the flower. Blow out the candle. Long and slow. Three times.” Do it with the class, not from the front.',
             ['Exhale longer than inhale', 'Shoulders drop', 'Gesture copied'],
             ['If silliness: model silently once, then invite them back.'],
             ['Breathe audibly beside any student who cannot settle'],
             ['No language demand; gesture carries it', 'Same two gestures used in every K–2 lesson'],
             'LiveSchool: award a point to a student who breathes all three times with you. Name the behavior: “You breathed slow three times.”',
             ''),
            ('Orient · The Story', 'R2, R3',
             'Point to each picture as you tell it. “Malik was mad. He hit Nadege. Ouch! Nadege got hurt and felt sad. Malik could use gentle hands. Then everyone can play safe and have fun.” Then have the class say together: “Hitting hurts. We use gentle hands.”',
             ['Students follow the pictures in order', 'Whole class repeats the We say line'],
             ['If students laugh at the hurt picture: pause, point to Nadege’s face, ask “How does her face look?”'],
             ['Point to each panel as the teacher narrates'],
             ['Four pictures, three words each; numbers carry the order', 'Act out “Ouch” by holding your own arm'],
             'Equity stick: “Which picture shows gentle hands? Point.” Pointing is a full answer.',
             'Keep the focus on what Malik can do next time. He is learning, just like us.'),
            ('Connect · Turn and Talk', 'R3, R4',
             'Show knee to knee with a student partner. “Turn knee to knee. Look at Nadege. Tell your partner: She feels ___.” Give 30 seconds, then ring back.',
             ['Partners face each other', 'Most students say “sad” or point to the sad face', 'Partners take turns'],
             ['If a pair is stuck: kneel in and say the stem with them.', 'If partners argue: “Take turns. You go first, then you.”'],
             ['Pair any student who needs support with a steady partner before the lesson starts'],
             ['Pointing to a face is a complete answer', 'Spanish: triste · Kreyòl: tris'],
             'Equity stick: call two names to share. Praise the frame: “You said: She feels sad. Full sentence!”',
             ''),
            ('Practice · Watch Me, Then Show Me', 'R3, R4, R5',
             'Read the scene. “A friend takes my truck. I feel mad. I can…” Invite one student to model: show a mad face, then pick a calm move from the row and do it. Narrate what you see and ask the class, “What did they do?” Then the whole class practices together.',
             ['A student models a mad face and then a calm move', 'Class names the calm move', 'Whole class rehearses deep breaths and “Can I have a turn?”'],
             ['Excellent model: “Show the class again. Everyone, what calm move did you see?”', 'Partly right model: “You showed the mad face. Now show us the calm move. Try again.”', 'Silly model: “Thank you. Let’s see it the safe way.” Call a new student; no commentary.'],
             ['Stand near the calm corner so students can point to the real one'],
             ['Five pictures; students can point instead of naming', 'Model “Can I have a turn?” as a sentence everyone says'],
             'LiveSchool: award the student model a point for showing a calm move. Name it out loud.',
             'Students model, not the teacher. The teacher narrates and asks the class what they saw.'),
            ('Commit · My Promise Today', 'R2, R5',
             'Put your hand on your heart. “Say it with me: I use gentle hands.” Then: “Point to the calm move you will use today when you feel mad.”',
             ['Every student says the promise', 'Every student points to one choice'],
             ['If a student does not choose: offer two pictures and let them point.'],
             ['Notice and name a student’s promise later in the day'],
             ['Hand on heart carries the promise', 'Spanish: Uso manos suaves · Kreyòl: Mwen sèvi ak men dous'],
             'Equity stick: pull three names: “Which one did you pick?” Pointing counts.',
             ''),
            ('Transition · How We Leave', 'R1, R4, R5',
             '“How we leave is how we start our learning. Stand up. Gentle hands. Walk. Ready to learn. Let’s practice.” Do not time this at K–2.',
             ['Hands to self while moving', 'Calm walking, not rushing'],
             ['“Let’s try that again. Back to your spot.” Rebuild clean, no commentary on individuals.'],
             ['Stand at the destination, not behind the group'],
             ['Four icons, four words', 'No timing pressure at this age'],
             'LiveSchool: award a point to the table that walks with gentle hands the whole way.',
             'Gentle hands all day: look for it at centers, in line, and at recess, and name it when you see it.'),
        ]),

    poster=dict(
        header_img='welcome', foot_img='thumbs',
        panels=[  # (art, color, symbol, EN, ES, KR, position)
            ('malik_fists', 'var(--red)', '✋', 'Hitting hurts. We do not hit.', 'Pegar duele. No pegamos.', 'Frape fè mal. Nou pa frape.', 'center 35%'),
            ('nadege_hurt', 'var(--sky)', '💧', 'My friend gets hurt and feels sad.', 'Mi amiga se lastima y se siente triste.', 'Zanmi m blese epi li santi l tris.', 'center 35%'),
            ('high_five', 'var(--green)', '✓', 'I use gentle hands.', 'Uso manos suaves.', 'Mwen sèvi ak men dous.', 'center 12%'),
            ('building', 'var(--orange)', '♥', 'Gentle hands keep us safe.', 'Las manos suaves nos cuidan.', 'Men dous pwoteje nou.', 'center 35%'),
        ]),

    minibook=dict(
        cover_title='My Gentle<br>Hands', cover_img='high_five', cover_pos='center 15%',
        cover_lang='<b>ES</b>Mis manos suaves · <b>KR</b>Men dous mwen',
        pages=[  # (art or (art1, art2), EN, ES, KR, position)
            ('building', 'I go to school. I play with my friends.', 'Voy a la escuela. Juego con mis amigos.', 'Mwen ale lekòl. Mwen jwe ak zanmi m yo.', 'center 40%'),
            ('tee_mad', 'Sometimes I feel mad. That is okay.', 'A veces me enojo. Está bien.', 'Pafwa mwen fache. Sa pa grav.', 'center 30%;background-size:contain'),
            ('nadege_hurt', 'If I hit, my friend gets hurt. Hitting hurts.', 'Si pego, mi amiga se lastima. Pegar duele.', 'Si m frape, zanmi m blese. Frape fè mal.', '40% 35%'),
            ('c_breathe', 'When I feel mad, I stop. I take deep breaths.', 'Cuando me enojo, paro. Respiro profundo.', 'Lè m fache, mwen kanpe. Mwen respire fon.', 'center 30%'),
            (('c_corner', 'c_grownup'), 'I can go to the calm corner. I can ask a grown-up.', 'Puedo ir al rincón de calma. Puedo pedir ayuda a un adulto.', 'Mwen ka ale nan kwen kalm nan. Mwen ka mande yon granmoun èd.', 'center 30%'),
            ('kiara_hi5', 'I use gentle hands. My friends feel safe. We play together!', 'Uso manos suaves. Mis amigos se sienten seguros. ¡Jugamos juntos!', 'Mwen sèvi ak men dous. Zanmi m yo santi yo an sekirite. Nou jwe ansanm!', 'center 30%'),
        ],
        back_img='promise', back_prompt='Color a star when I use gentle hands.'),

    centers=dict(
        sort=dict(title='SORT IT: GENTLE OR NOT GENTLE?',
                  yes=('✓', 'Gentle hands', 'Manos suaves', 'Men dous'),
                  no=('✋', 'Not gentle', 'No son suaves', 'Pa dous'),
                  cards=[('high_five', 'center 15%'), ('building', 'center 40%'), ('ball', 'center 40%'), ('puzzle', 'center 40%'),
                         ('handing', 'center 40%'), ('malik_fists', '68% 40%'), ('nadege_throw', '75% 40%'), ('diego_fists', '30% 35%')]),
        seq=dict(cards=['to_corner', 'in_corner', 'to_rug', 'building'], shuffle=[2, 0, 3, 1]),
        roleplay=dict(prompt='I feel mad. I can...', scenes=[
            ('malik_fists', '68% 40%', 'A friend takes my truck.', 'Un amigo toma mi camión.', 'Yon zanmi pran kamyon m.'),
            ('tower_falls', 'center 45%', 'My tower falls down.', 'Mi torre se cae.', 'Gwo kay blòk mwen tonbe.'),
            ('leave', 'center 40%', 'A friend bumps me in line.', 'Un amigo me empuja en la fila.', 'Yon zanmi frape m nan liy lan.'),
            ('ball', 'center 40%', 'I want a turn with the ball.', 'Quiero un turno con la pelota.', 'Mwen vle yon tou ak boul la.')]),
        strip=dict(title='DESK STRIPS: MY CALM CHOICES'),
        coloring=dict(title='I USE GENTLE HANDS', art='color_b.png',
                      prompt='Draw a gentle hands move you can do:',
                      prompt_lang='ES Dibuja algo suave que puedes hacer con tus manos. · KR Desine yon fason ou ka sèvi ak men dous.'),
    ),

    family=dict(hero='high_five', langs={
        'en': dict(t='Gentle Hands', eb='This week in Morning Meeting · Kindergarten to 2nd Grade',
                   intro='Your child is learning that hitting hurts and that gentle hands keep everyone safe. Big feelings are okay. Children are practicing calm choices for when they feel mad.',
                   sayh='At school we say:', say='Hitting hurts. We use gentle hands.', ch='Calm choices', th='Try at home',
                   tips=['<b>Breathe together:</b> smell the flower, blow out the candle. Three times.', '<b>Ask:</b> “What can you do when you feel mad?” Let your child point to a calm choice.', '<b>Notice it:</b> “You used gentle hands with your sister!”'],
                   ft='Questions? Talk with your child’s teacher.'),
        'es': dict(t='Manos suaves', eb='Esta semana en la Reunión de la Mañana · Kínder a 2.º grado',
                   intro='Su hijo o hija está aprendiendo que pegar duele y que las manos suaves nos mantienen seguros. Está bien tener sentimientos fuertes. Los niños practican opciones de calma para cuando se enojan.',
                   sayh='En la escuela decimos:', say='Pegar duele. Usamos manos suaves.', ch='Opciones de calma', th='Practiquen en casa',
                   tips=['<b>Respiren juntos:</b> huelan la flor, soplen la vela. Tres veces.', '<b>Pregunte:</b> “¿Qué puedes hacer cuando te enojas?” Deje que su hijo o hija señale una opción de calma.', '<b>Fíjese y felicite:</b> “¡Usaste manos suaves con tu hermana!”'],
                   ft='¿Preguntas? Hable con el maestro o la maestra de su hijo o hija.'),
        'kr': dict(t='Men dous', eb='Semèn sa a nan Reyinyon Maten · Kindègadenn rive 2yèm ane',
                   intro='Pitit ou ap aprann ke frape fè mal, epi men dous pwoteje tout moun. Li nòmal pou yon timoun santi gwo santiman. Timoun yo ap pratike chwa pou yo kalme lè yo fache.',
                   sayh='Nan lekòl la nou di:', say='Frape fè mal. Nou sèvi ak men dous.', ch='Chwa pou kalme', th='Eseye lakay ou',
                   tips=['<b>Respire ansanm:</b> pran sant flè a, soufle bouji a. Twa fwa.', '<b>Mande:</b> “Kisa ou ka fè lè ou fache?” Kite pitit ou montre yon chwa pou kalme.', '<b>Remake l:</b> “Ou te sèvi ak men dous ak sè w!”'],
                   ft='Ou gen kesyon? Pale ak pwofesè pitit ou a.'),
    }),

    guide=dict(
        images=[('high_five', 170, 170), ('malik_fists', 300, 168)],
        glance=[
            ('Goal', 'Students say “Hitting hurts. We use gentle hands” and choose a calm move when they feel mad.'),
            ('Time', '15 minutes in Morning Meeting, in place of the general lesson. Centers run during the week.'),
            ('When', 'Teach before trouble. If a child in this room was hit today, wait a day.'),
            ('In the bundle', 'Student deck (7 slides, press N for notes) · Poster (letter and 11×17) · Center kit (sort, sequence, act it out, desk strips, coloring) · Mini book · Family half-sheet'),
            ('Words we use', '“Hitting hurts. We use gentle hands.” · “When I feel mad, I can…” · “Can I have a turn?”'),
        ],
        before=[
            'Hang the poster at child height near the calm corner. Students point to it all week.',
            'The story uses Malik and Nadege, the toolkit’s classmates. Never cast a real student as the child who hits.',
            'Tape a desk strip at the table of any student who needs the calm choices close by.',
            'Pair students who need support with a steady turn-and-talk partner before the lesson starts.',
        ],
        slides=[
            ('1 · Title & Promise (R2)', 'Hold up both open hands and wiggle the fingers. “These are my hands. Today we learn how our hands keep our friends safe. Show me your hands.”', 'Every student shows open hands.', 'Equity stick: “Show me gentle hands.” Praise any calm open hands.'),
            ('2 · Get Calm First (R1)', 'Do it with them. “Smell the flower. Blow out the candle. Long and slow. Three times.”', 'Exhale longer than inhale; shoulders drop.', 'LiveSchool point: “You breathed slow three times.”'),
            ('3 · What Happened? (R2, R3)', 'Point to each picture. “Malik was mad. He hit Nadege. Ouch! Nadege got hurt and felt sad. Malik could use gentle hands. Then everyone can play safe.” Class says: “Hitting hurts. We use gentle hands.”', 'Students follow the pictures; whole class repeats the line.', 'Equity stick: “Which picture shows gentle hands? Point.”'),
            ('4 · Turn and Talk (R3, R4)', 'Model knee to knee. “Look at Nadege. Tell your partner: She feels ___.” 30 seconds, then ring back.', 'Partners face each other and take turns; most say or point to “sad.”', 'Equity stick: two shares. Praise the full sentence.'),
            ('5 · Watch Me, Then Show Me (R3, R4, R5)', 'Read: “A friend takes my truck. I feel mad. I can…” A student models a mad face, then a calm move. Ask the class, “What did they do?” Then everyone rehearses deep breaths and “Can I have a turn?”', 'A student models; class names the calm move; whole class rehearses.', 'LiveSchool point for the student model. Name the calm move out loud.'),
            ('6 · My Promise Today (R2, R5)', 'Hand on heart. “Say it with me: I use gentle hands.” Then: “Point to the calm move you will use today.”', 'Every student says the promise and points to one choice.', 'Equity stick: three names. Pointing counts.'),
            ('7 · How We Leave (R1, R4, R5)', '“Stand up. Gentle hands. Walk. Ready to learn.” Do not time this at K–2.', 'Hands to self while moving; calm walking.', 'LiveSchool point for the table that walks with gentle hands the whole way.'),
        ],
        bridges=[
            ('Excellent', '“Show the class again. Everyone, what calm move did you see?” Then the whole class does it together.'),
            ('Partly right', '“You showed the mad face. Now show us the calm move. Try again.”'),
            ('Silly', '“Thank you. Let’s see it the safe way.” Call a new student. No commentary.'),
        ],
        centers=[
            ('Sort It', 'Sort mat (landscape page) and 8 cut picture cards.', '“Look at each picture. Is it gentle hands or not gentle? Put it on the side where it goes.”', '5 cards on Gentle, 3 on Not gentle.'),
            ('Put It in Order', 'Sequencing mat and 4 cut cards.', '“Put the pictures in order: first, next, then, last. Tell your partner the story.”', 'Students retell: mad, calm corner, back to the rug, play.'),
            ('Act It Out', '4 role-play cards in a stack.', '“Pick a card. Read it with me. Show a mad face. Then show a calm move from the pictures.”', 'Each student shows one calm move.'),
            ('Calm Choices', 'Desk strips, one per student.', '“Point to the calm choice you like best. Show me how you do it.”', 'Each student points and acts out one choice.'),
            ('Color', 'Coloring page and crayons.', '“Color Lee and Tee. In the box, draw a gentle hands move you can do.”', 'A drawing of a high five, a wave, or a fist bump.'),
        ],
        keys=[
            ('Sort, Gentle hands: ', 'Lee and Tee high five · friends building with blocks · Tee and Malik tossing a ball · Tee and Nadege doing a puzzle · Tee handing Kiara a block.'),
            ('Sort, Not gentle: ', 'Malik with tight fists over the truck · Nadege about to throw a block · Diego with fists at the teacher.'),
            ('Put It in Order: ', '1 Tee walks to the calm corner, mad · 2 Tee calms down in the corner · 3 Tee walks back to the rug · 4 friends play together.'),
        ],
        minibook=[
            'For a child who has hit more than once. Read it one-on-one, at a calm time, before the hardest part of the day.',
            'Read it every day for a week. Let the child turn the pages and point to the calm choices.',
            'Never read it as a consequence or right after an incident.',
            'On the back, the child colors a star each day they use gentle hands. Celebrate every star.',
        ],
        when_title='When it happens',
        when_intro='Follows the Responsive Behavior Plan: the adult response is the intervention. Fewer words as escalation rises.',
        when=[
            ('Safety first. ', 'Calmly step between. Care for the hurt child first: “Are you okay? Let’s get you help.”'),
            ('Few words. ', 'To the child who hit: “Hands down. Come with me.” Offer a break: break, reset, return. If hitting continues or anyone is in danger, call for support.'),
            ('Address, once calm. ', 'Point to the poster. “Hitting hurts. Next time, pick a calm choice.” Correct the routine, not the child.'),
            ('Document. ', 'Fill out the Live Card right away: facts only, in bullet points.'),
            ('Repair, after regulation. ', '“I can see you were mad. Who got hurt? What can we do to help?” K–2 repair can be checking on the friend, helping rebuild, or drawing a picture. Never force an apology.'),
            ('Reflect. ', 'If it happens again, share the Live Cards with your coach and the counseling team.'),
        ],
        when_outro='If a student hits an adult, use Topic 8, Gentle Hands with Grown-Ups, and the same pathway.',
    ),

    site=dict(card_img='high_five', line='I use gentle hands. I keep my friends safe.',
              hero_img='high_five', hero_alt='Two friends giving a gentle high five',
              story_desc='Get calm, watch the story, turn and talk, practice, make a promise, and leave calmly.',
              centers_desc='Sort mat and 8 picture cards, sequencing mat and cards, role-play cards, desk strips, and a coloring page.',
              minibook_desc='A private, read-together story for students who need more practice. Read it one on one or in a small group.',
              guide_desc='The lesson at a glance, the slide-by-slide script, how to run the centers, and what to do when it happens.',
              family_desc='What your child is learning, what we say at school, and three things to try at home. One page per language, two half-sheets per page.',
              poster_hint='Hang it at student eye level near your meeting space.'),
)
